language: python
sudo: false
python:
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install --upgrade setuptools
  - pip install coveralls
  - pip install -Ur requirements-dev.txt
  - python setup.py develop

script:
  make cov
after_success:
  coveralls

env:
  matrix:
    - PYTHONASYNCIODEBUG=1
    - PYTHONASYNCIODEBUG=0
